site_name: Proyecto Física Computacional, Modelo de un capacitor

theme: 
  name: "material"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav: 
  - Home: index.md
  - Explanation: explanation.md
  - Reference: reference.md
  - Tutorial: tutorials.md

plugins:  
  - mkdocstrings
